version: '3.8'

services:
  #FPM Service
  blackjack-fpm:
    image: php:8.1.0-fpm-alpine
    container_name: blackjack-fpm
    volumes:
      - .:/var/www
      - ./docker/php80/www.conf:/etc/php/8.0/fpm/pool.d/www.conf
    restart: always
    working_dir: /var/www
    networks:
      - app-network

  #NGINX Service
  blackjack-nginx:
    container_name: blackjack-nginx
    image: nginx:1.18
    volumes:
      - .:/var/www
      - ./docker/nginx/vhosts/:/etc/nginx/conf.d/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    working_dir: /var/www
    networks:
      - app-network
    ports:
      - 80:80

networks:
  app-network:
    driver: bridge
    name: blackjacknetw
